config/routes.rb
Rails.application.routes.draw do
  resources :site_events, only: [:index, :create], defaults: { format: :js }

  devise_for :users, :controllers => { registrations: "registrations" }

  resources :sites

  get "admin" => "admin#index"
  namespace :admin do
    resources :users
    resources :sites
  end

  root to: "home#index"
end

app/views/shared/_admin_menu.html.erb
<% if current_user.is_admin? %>
<li class="dropdown">
    <%= link_to "<span class=\"fa fa-cog\"></span> Admin <span class=\"caret\"></span>".html_safe, "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
    <ul class="dropdown-menu">
      <li><%= link_to "Users", admin_users_path %></li>
      <li><%# link_to "Sites", admin_sites_path %></li>
    </ul>
</li>
<% end %>

app/views/shared/_breadcrumbs.html.erb
<ul class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
</ul>

app/views/shared/_footer.html.erb
<footer id="footer navbar navbar-default">
    <div class="container">
        <p class="text-muted pull-left">Copyright &copy; <%= Date.today.year %> <%= t("branding.site_name") %></p>

        <!-- <ul class="list-inline center-block pull-right">
            <li><a href="http://facebook.com/"><i class="fa fa-twitter"></i></a></li>
            <li><a href="http://twitter.com/"><i class="fa fa-facebook"></i></a></li>
            <li><a href="http://pinterest.com/"><i class="fa fa-pinterest"></i></a></li>
            <li><a href="mailto://"><i class="fa fa-envelope"></i></a></li>
        </ul> -->
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<span class=\"fa fa-bar-chart\"></span> WRULA".html_safe, root_url, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_url %></li>
          <%= render "shared/admin_menu" %>
          <%= render "shared/profile_menu" %>
          <li><%= link_to t("devise.buttons.signout"), destroy_user_session_path, method: :delete %></li>
        <% else %>

          <li><%= link_to t("devise.buttons.signup"), new_user_registration_path %></li>
          <li><%= link_to t("devise.buttons.signin"), new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/shared/_profile_menu.html.erb
<li class="dropdown">
  <%= link_to "#{current_user} <span class=\"caret\"></span>".html_safe, "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
  <ul class="dropdown-menu">
    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
    <li class="divider"></li>
    <li class="dropdown-header">My Sites</li>
    <li><%= link_to "View Sites", sites_path %></li>
    <li><%= link_to "New Site", new_site_path %></li>
  </ul>
</li>