config/routes.rb
Rails.application.routes.draw do
  resources :site_events, only: [:index, :create], defaults: { format: :js }

  devise_for :users, :controllers => { registrations: "registrations" }

  resources :sites

  get "admin" => "admin#index"
  namespace :admin do
    resources :users
    resources :sites
  end

  root to: "home#index"
end

app/models/site.rb
require 'uri'

class Site < ActiveRecord::Base
  belongs_to :user

  has_many :site_events, dependent: :destroy

  validates :name, presence: true

  before_save :set_account_id

  def set_account_id
    # we could do this on create, but often times things
    # happen during the save, so rather than creating a
    # method to compensate for it, we'll call the method
    # on any save, and just noop if it's already set
    return if self.account_id

    # loop until the token (account_id) generated is unique
    self.account_id = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Site.exists?(account_id: random_token)
    end
  end

  def get_unique_count_by(start_date, end_date, column)
    # return the number of unique values stored for the provided column
    self.get_unique_by(start_date, end_date, column).count()
  end

  def get_unique_by(start_date, end_date, column)
    # returns
    self.site_events.where(created_at: start_date.to_date..end_date.to_date).group("payload -> '#{column}'")
  end

  def get_daily_visits(start_date, end_date)
    # returns an active record result set representing each day between
    # the provided start and end date for each page, and how many times
    # that page has been viewed

    # TODO: potentially move this to a stored procedure, the reason we're
    # using raw sql here is so that we can join it against a psuedo table
    # that ensures a value is returned for every page, for every day that
    # lies between the provided start and end date
    query = "SELECT *
    FROM (
      SELECT day::date
      FROM generate_series(timestamp '#{start_date.to_s(:db)}', timestamp '#{end_date.to_s(:db)}', interval '1 day') as day
    ) d
    LEFT JOIN (
      SELECT CAST(site_events.created_at as DATE) as day, count(id)
      FROM site_events
      WHERE site_id = #{self.id}
      GROUP BY day
    ) t USING (day)
    ORDER BY day"

    ActiveRecord::Base.connection.execute(query)
  end

  class << self

    def parse_full_url(provided_url)
      # URI does a nice job of parsing the data out, this is just a more
      # hydrated version of its result, for thr purpose of storing it
      url = URI(provided_url)
      {
          "url": url.to_s,
          "host": url.host,
          "path": url.path,
          "query": url.query
      }
    end

  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # after_action  :verify_authorized

  # GET /sites
  def index
    @sites = current_user.sites.all
  end

  # GET /sites/1
  def show
    @start_date = if params[:start_date]
      Date.parse(params[:start_date])
    else
      6.days.ago.to_date
    end

    @end_date = if params[:end_date]
      DateTime.parse(params[:end_date])
    else
      DateTime.now
    end.end_of_day

    # table data
    @popular_pages = SiteEvent.select("payload -> 'path' as path, count('path')").where(site: @site).where(created_at: @start_date..@end_date).group('path').order("count DESC")
    @page_visit_data = @site.get_daily_visits(@start_date, @end_date)

    # tab data
    @browser_breakdown = SiteEvent.select("payload -> 'browser' as browser, count('browser')").where(site: @site).where(created_at: @start_date..@end_date).group('browser').order("count DESC")
    @os_breakdown = SiteEvent.select("payload -> 'platform' as platform, count('platform')").where(site: @site).where(created_at: @start_date..@end_date).group('platform').order("count DESC")
    @ip_breakdown = SiteEvent.select("payload -> 'ip' as ip, count('ip')").where(site: @site).where(created_at: @start_date..@end_date).group('ip').order("count DESC")
    @user_status_breakdown = SiteEvent.select("payload -> 'is_returning' as is_returning, count('is_returning')").where(site: @site).where(created_at: @start_date..@end_date).group('is_returning').order("count DESC")

  end

  # GET /sites/new
  def new
    @site = current_user.sites.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  def create
    @site = current_user.sites.new(site_params)

    if @site.save
      redirect_to @site, notice: 'Site was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sites/1
  def update
    if @site.update(site_params)
      redirect_to @site, notice: 'Site was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sites/1
  def destroy
    @site.destroy
    redirect_to sites_url, notice: 'Site was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = current_user.sites.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def site_params
      params.require(:site).permit(:user_id, :name, :url, :account_id)
    end
end

app/views/sites/_browsers.html.erb
<div class="row">
    <div class="col-sm-9">
        <h3>Page Views By Browser</h3>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Browser</th>
                    <th class="col-xs-2">Views</th>
                </tr>
            </thead>
            <tbody>
                <% @browser_breakdown.each do |page| %>
                <tr>
                    <td><%= page.browser %></td>
                    <td class="col-xs-2"><%= number_with_delimiter(page.count) %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="col-sm-3">
        <div class="panel panel-default">
            <div class="panel-heading">Browsers</div>
            <div class="panel-body">
                <div id="browser-chart" class="chart contains-chart"></div>
            </div>
        </div>
    </div>
</div>

<% content_for :footer_javascript do %>
    // Make monochrome colors and set them as default for all pies
    Highcharts.getOptions().plotOptions.pie.colors = (function () {
        var colors = [],
            base = Highcharts.getOptions().colors[0],
            i;

        for (i = 0; i < 10; i += 1) {
            // Start out with a darkened base color (negative brighten), and end
            // up with a much brighter color
            colors.push(Highcharts.Color(base).brighten((i - 3) / 7).get());
        }
        return colors;
    }());

    $('#browser-chart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: null
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false
                },
                // showInLegend: true
            }
        },
        series: [{
            name: 'Browsers',
            colorByPoint: true,
            data: <%= @browser_breakdown.map { |b| {name: b.browser, y: b.count} }.to_json.html_safe %>
        }],
        credits: false,
        yAxis: {
            title: {
                text: null
            }
        }
    });
<% end %>

app/views/sites/_form.html.erb
<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control", placeholder: "http://fullsiteurl.com" %>
  </div>
</div>

app/views/sites/_installation.html.erb
<div class="well well-sm text-center">
    <h4>Installing <%= t("branding.site_name") %> Analytics</h4>
    <p>To begin collecting data for this site, copy and paste the code below into every webpage you want to track.</p>

    <code>
        <%= raw (CGI::escapeHTML content_tag(:script, nil, type: "text/javascript", src: site_events_url(account_id: site.account_id))) %>
    </code>
</div>

app/views/sites/_operating_systems.html.erb
<div class="row">
    <div class="col-sm-9">
        <h3>Page Views By Operating System</h3>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Browser</th>
                    <th class="col-xs-2">Views</th>
                </tr>
            </thead>
            <tbody>
                <% @os_breakdown.each do |page| %>
                <tr>
                    <td><%= page.platform %></td>
                    <td class="col-xs-2"><%= number_with_delimiter(page.count) %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="col-sm-3">
        <div class="panel panel-default">
            <div class="panel-heading">Operating Systems</div>
            <div class="panel-body">
                <div id="os-chart" class="chart contains-chart"></div>
            </div>
        </div>
    </div>
</div>

<% content_for :footer_javascript do %>
    // Make monochrome colors and set them as default for all pies
    Highcharts.getOptions().plotOptions.pie.colors = (function () {
        var colors = [],
            base = Highcharts.getOptions().colors[0],
            i;

        for (i = 0; i < 10; i += 1) {
            // Start out with a darkened base color (negative brighten), and end
            // up with a much brighter color
            colors.push(Highcharts.Color(base).brighten((i - 3) / 7).get());
        }
        return colors;
    }());

    $('#os-chart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: null
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false
                },
                // showInLegend: true
            }
        },
        series: [{
            name: 'Browsers',
            colorByPoint: true,
            data: <%= @os_breakdown.map { |b| {name: b.platform, y: b.count} }.to_json.html_safe %>
        }],
        credits: false,
        yAxis: {
            title: {
                text: null
            }
        }
    });
<% end %>

app/views/sites/_pages.html.erb
<div class="row">
    <div class="col-xs-12">
        <h3>Page Views</h3>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Page</th>
                    <th class="col-xs-2">Views</th>
                </tr>
            </thead>
            <tbody>
                <% @popular_pages.each do |page| %>
                <tr>
                    <td><%= page.path %></td>
                    <td class="col-xs-2"><%= number_with_delimiter(page.count) %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/sites/_users.html.erb
<div class="row">
    <div class="col-sm-9">
        <h3>Page Views By IP Address</h3>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>IP Address</th>
                    <th class="col-xs-2">Views</th>
                </tr>
            </thead>
            <tbody>
                <% @ip_breakdown.each do |page| %>
                <tr>
                    <td><%= page.ip %></td>
                    <td class="col-xs-2"><%= number_with_delimiter(page.count) %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="col-sm-3">
        <div class="panel panel-default">
            <div class="panel-heading">New vs Returning Users</div>
            <div class="panel-body">
                <div id="ip-chart" class="chart contains-chart"></div>
            </div>
        </div>
    </div>
</div>

<% content_for :footer_javascript do %>
    // Make monochrome colors and set them as default for all pies
    Highcharts.getOptions().plotOptions.pie.colors = (function () {
        var colors = [],
            base = Highcharts.getOptions().colors[0],
            i;

        for (i = 0; i < 10; i += 1) {
            // Start out with a darkened base color (negative brighten), and end
            // up with a much brighter color
            colors.push(Highcharts.Color(base).brighten((i - 3) / 7).get());
        }
        return colors;
    }());

    $('#ip-chart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: null
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'IP Addresss',
            colorByPoint: true,
            data: <%= @user_status_breakdown.map { |b| {name: b.is_returning ? "Returning" : "New", y: b.count, sliced: !b.is_returning } }.to_json.html_safe %>
        }],
        credits: false,
        yAxis: {
            title: {
                text: null
            }
        }
    });
<% end %>

app/views/sites/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1 class="page-header">Edit <%= @site.name %></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <%= render partial: "installation", locals: { site: @site } %>
        </div>
    </div>

    <%= form_for(:site, url: site_path(@site), html: { method: :patch }) do |f| %>
        <div class="row">
            <div class="col-xs-12">
                <%= errors_for(@site) %>
            </div>
        </div>

        <%= render "form", f: f %>

        <div class="row">
            <div class="col-sm-2">
                <%= link_to 'Delete This Site', @site, method: :delete, class: "btn btn-danger btn-block", data: { confirm: 'Are you sure you want to delete this site and all associated data?' } %>
            </div>

            <div class="col-sm-2 col-sm-offset-8">
                <%= f.submit class: "btn btn-primary btn-block" %>
            </div>
        </div>
    <% end %>
</div>

app/views/sites/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="page-header">Your Sites</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Url</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @sites.each do |site| %>
            <tr>
              <td><%= site.name %></td>
              <td><%= site.url %></td>
              <td class="col-xs-1"><%= link_to 'Show', site %></td>
              <td class="col-xs-1"><%= link_to 'Settings', edit_site_path(site) %></td>
              <td class="col-xs-1"><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure you want to delete this site and all associated data?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/sites/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1 class="page-header">New Site</h1>
        </div>
    </div>

    <%= form_for(:site, url: sites_path, html: { method: :post }) do |f| %>
        <div class="row">
            <div class="col-xs-12">
                <%= errors_for(@site) %>
            </div>
        </div>

        <%= render "form", f: f %>

        <div class="row">
            <div class="col-sm-2 col-sm-offset-10">
                <%= f.submit class: "btn btn-primary btn-block" %>
            </div>
        </div>
    <% end %>
</div>

app/views/sites/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-8 col-md-9">
                        <h1><%= @site.name %> <small><%= @site.url %></small></h1>
                    </div>
                    <div class="col-sm-4 col-md-3">
                        <div class="btn-group btn-group-justified">
                            <%= link_to "Settings", edit_site_path(@site), class: "btn btn-success" %>

                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    Sites <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <% current_user.sites.each do |site| %>
                                    <li><%= link_to site.name, site_path(site) %></li>
                                    <% end %>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <% unless @site.site_events.any? %>
    <div class="row">
        <div class="col-xs-12">
            <%= render partial: "installation", locals: { site: @site } %>
        </div>
    </div>
    <% end %>

    <div class="row">
        <div class="col-xs-12">
            <div class="well date-selector clearfix">
                <form>
                    <div class="row">
                        <div class="col-sm-6 hidden-xs">
                            <h4><%= @start_date.strftime("%B %d, %Y") %> <small> to </small> <%= @end_date.strftime("%B %d, %Y") %></h4>
                        </div>
                        <div class="form-group col-sm-4 ">
                            <div class="input-daterange input-group">
                                <input type="text" class="form-control" name="start_date" value="<%= @start_date.to_s(:db) %>" />
                                <span class="input-group-addon">to</span>
                                <input type="text" class="form-control" name="end_date" value="<%= @end_date.to_date.to_s(:db) %>" />
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-primary btn-block">Refresh</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div id="page-view-chart" class="chart"></div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row metric-row">
        <div class="col-xs-12 col-sm-4">
            <div class="panel panel-default">
                <div class="panel-body metric-panel text-center">
                    <%= number_with_delimiter(@site.site_events.where(created_at: @start_date..@end_date).count()) %>
                </div>
                <div class="panel-footer text-center">
                    Total Visits
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-2">
            <div class="panel panel-default">
                <div class="panel-body metric-panel text-center">
                    <%= @site.get_unique_count_by(@start_date, @end_date, "path").count() %>
                </div>
                <div class="panel-footer text-center">
                    Pages
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-2">
            <div class="panel panel-default">
                <div class="panel-body metric-panel text-center">
                    <%= @site.get_unique_count_by(@start_date, @end_date, "browser").count() %>
                </div>
                <div class="panel-footer text-center">
                    Browsers
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-2">
            <div class="panel panel-default">
                <div class="panel-body metric-panel text-center">
                    <%= @site.get_unique_count_by(@start_date, @end_date, "platform").count() %>
                </div>
                <div class="panel-footer text-center">
                    Operating Systems
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-2">
            <div class="panel panel-default">
                <div class="panel-body metric-panel text-center">
                    <%= @site.get_unique_count_by(@start_date, @end_date, "ip").count() %>
                </div>
                <div class="panel-footer text-center">
                    Users
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#pages" aria-controls="pages" role="tab" data-toggle="tab">Pages</a>
                </li>
                <li role="presentation">
                    <a href="#browsers" aria-controls="browsers" role="tab" data-toggle="tab">Browsers</a>
                </li>
                <li role="presentation">
                    <a href="#operating_systems" aria-controls="operating_systems" role="tab" data-toggle="tab">Operating Systems</a>
                </li>
                <li role="presentation">
                    <a href="#users" aria-controls="users" role="tab" data-toggle="tab">Users</a>
                </li>
            </ul>

            <div class="tab-content">
                <!-- Pages Content -->
                <div role="tabpanel" class="tab-pane active" id="pages">
                <%= render partial: "pages" %>
                </div>

                <!-- Browsers Content -->
                <div role="tabpanel" class="tab-pane" id="browsers">
                <%= render partial: "browsers" %>
                </div>

                <!-- OS Content -->
                <div role="tabpanel" class="tab-pane" id="operating_systems">
                <%= render partial: "operating_systems" %>
                </div>

                <!-- Users Content -->
                <div role="tabpanel" class="tab-pane" id="users">
                    <%= render partial: "users" %>
                </div>
            </div>
        </div>
    </div>
</div>

<% content_for :footer_javascript do %>
    $('.input-daterange').datepicker({
        todayBtn: "linked",
        autoclose: true,
        todayHighlight: true,
        endDate: "today",
        startDate: "-1y",
        format: "yyyy-mm-dd"
    });

    $('#page-view-chart').highcharts({
        chart: {
            type: 'area'
        },
        title: {
            text: null
        },
        plotOptions: {
            area: {
                showInLegend: false
            }
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: {
                month: '%e. %b',
                year: '%b'
            },
            title: {
                text: null
            }
        },
        yAxis: {
            title: {
                text: null
            }
        },
        tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%B %e, %Y}: {point.y} Views'
        },
        series: [
            {
                name: 'Page Views Per Day',
                data: <%= @page_visit_data.map { |d| [(Time.parse(d["day"]).to_f * 1000), d["count"].to_i] }.to_json.html_safe %>
            }
        ],
        credits: false
    });
<% end %>